version: "3"

services:
  # hazelcast-node-1:
  #   image: hazelcast/hazelcast:latest
  #   restart: unless-stopped
  #   environment:
  #     HZ_NETWORK_JOIN: hazelcast-node-2,hazelcast-node-3
  #     JAVA_OPTS: -Dhazelcast.config=/opt/hazelcast/config/hazelcast.xml
  #   volumes:
  #     - "./hazeclast.xml:/opt/hazelcast/config/hazelcast.xml"
  #   ports:
  #     - "5701:5701"
  #   networks:
  #     - hazelcast-lecture

  # hazelcast-node-2:
  #   image: hazelcast/hazelcast:latest
  #   restart: unless-stopped
  #   environment:
  #     HZ_NETWORK_JOIN: hazelcast-node-1,hazelcast-node-3
  #     JAVA_OPTS: -Dhazelcast.config=/opt/hazelcast/config/hazelcast.xml
  #   volumes:
  #     - "./hazeclast.xml:/opt/hazelcast/config/hazelcast.xml"
  #   ports:
  #     - "5702:5701"
  #   networks:
  #     - hazelcast-lecture

  # hazelcast-node-3:
  #   image: hazelcast/hazelcast:latest
  #   restart: unless-stopped
  #   environment:
  #     HZ_NETWORK_JOIN: hazelcast-node-1,hazelcast-node-2
  #     JAVA_OPTS: -Dhazelcast.config=/opt/hazelcast/config/hazelcast.xml
  #   volumes:
  #     - "./hazeclast.xml:/opt/hazelcast/config/hazelcast.xml"
  #   ports:
  #     - "5703:5701"
  #   networks:
  #     - hazelcast-lecture
    
  api-loggin-1:
    build: 
      context: .
      dockerfile: loggin.Dockerfile
    restart: unless-stopped
    environment:
      PORT_SEVICE: ${URL_LOGGIN_MACHINE_1}
    ports:
      - "${URL_LOGGIN_MACHINE_1}:${URL_LOGGIN_MACHINE_1}"
    networks:
      - hazelcast-lecture
  api-loggin-2:
    build: 
      context: .
      dockerfile: loggin.Dockerfile
    restart: unless-stopped
    environment:
      PORT_SEVICE: ${URL_LOGGIN_MACHINE_2}
    ports:
      - "${URL_LOGGIN_MACHINE_2}:${URL_LOGGIN_MACHINE_2}"
    networks:
      - hazelcast-lecture
  api-loggin-3:
    build: 
      context: .
      dockerfile: loggin.Dockerfile
    restart: unless-stopped
    environment:
      PORT_SEVICE: ${URL_LOGGIN_MACHINE_3}
    ports:
      - "${URL_LOGGIN_MACHINE_3}:${URL_LOGGIN_MACHINE_3}"
    networks:
      - hazelcast-lecture
  api-facade:
    build: 
      context: .
      dockerfile: facade.Dockerfile
    restart: unless-stopped
    environment:
      PORT_SEVICE: ${URL_FACADE_MACHINE}
      LOGGIN_1: ${URL_LOGGIN_MACHINE_1}
      LOGGIN_2: ${URL_LOGGIN_MACHINE_2}
      LOGGIN_3: ${URL_LOGGIN_MACHINE_3}
    ports:
      - "${URL_FACADE_MACHINE}:${URL_FACADE_MACHINE}"
    networks:
      - hazelcast-lecture
  api-message:
    build: 
      context: .
      dockerfile: message.Dockerfile
    restart: unless-stopped
    environment:
      PORT_SEVICE: ${URL_MESSAGE_MACHINE}
    ports:
      - "${URL_MESSAGE_MACHINE}:${URL_MESSAGE_MACHINE}"
    networks:
      - hazelcast-lecture

  hazelcast-management-center:
    image: hazelcast/management-center:latest
    restart: unless-stopped
    environment:
      - HZ_MAN_CENTER_CLUSTER_MEMBERS=hazelcast-node-1:5701,hazelcast-node-2:5701,hazelcast-node-3:5701
    ports:
      - "8080:8080"
    networks:
      - hazelcast-lecture

networks:
  hazelcast-lecture:
    driver: bridge
