version: "3"

services:
  hazelcast-node-1:
    image: hazelcast/hazelcast:latest
    environment:
      HZ_NETWORK_JOIN: hazelcast-node-2,hazelcast-node-3
      JAVA_OPTS: -Dhazelcast.config=/opt/hazelcast/config/hazelcast.xml
    volumes:
      - "./hazeclast.xml:/opt/hazelcast/config/hazelcast.xml"
    ports:
      - "5701:5701"
    networks:
      - hazelcast-lecture

  hazelcast-node-2:
    image: hazelcast/hazelcast:latest
    environment:
      HZ_NETWORK_JOIN: hazelcast-node-1,hazelcast-node-3
      JAVA_OPTS: -Dhazelcast.config=/opt/hazelcast/config/hazelcast.xml
    volumes:
      - "./hazeclast.xml:/opt/hazelcast/config/hazelcast.xml"
    ports:
      - "5702:5701"
    networks:
      - hazelcast-lecture

  hazelcast-node-3:
    image: hazelcast/hazelcast:latest
    environment:
      HZ_NETWORK_JOIN: hazelcast-node-1,hazelcast-node-2
      JAVA_OPTS: -Dhazelcast.config=/opt/hazelcast/config/hazelcast.xml
    volumes:
      - "./hazeclast.xml:/opt/hazelcast/config/hazelcast.xml"
    ports:
      - "5703:5701"
    networks:
      - hazelcast-lecture

  hazelcast-management-center:
    image: hazelcast/management-center:latest
    environment:
      - HZ_MAN_CENTER_CLUSTER_MEMBERS=hazelcast-node-1:5701,hazelcast-node-2:5701,hazelcast-node-3:5701
    ports:
      - "8080:8080"
    networks:
      - hazelcast-lecture

networks:
  hazelcast-lecture:
