version: "3"

services:
  hazelcast-node-1:
    image: hazelcast/hazelcast:latest
    restart: unless-stopped
    environment:
      HZ_NETWORK_JOIN: hazelcast-node-2,hazelcast-node-3
      JAVA_OPTS: -Dhazelcast.config=/opt/hazelcast/config/hazelcast.xml
    volumes:
      - "./hazeclast.xml:/opt/hazelcast/config/hazelcast.xml"
    ports:
      - "${PORT_NODE_HZ_1}:5701"
    networks:
      - hazelcast-lecture

  hazelcast-node-2:
    image: hazelcast/hazelcast:latest
    restart: unless-stopped
    environment:
      HZ_NETWORK_JOIN: hazelcast-node-1,hazelcast-node-3
      JAVA_OPTS: -Dhazelcast.config=/opt/hazelcast/config/hazelcast.xml
    volumes:
      - "./hazeclast.xml:/opt/hazelcast/config/hazelcast.xml"
    ports:
      - "${PORT_NODE_HZ_2}:5701"
    networks:
      - hazelcast-lecture

  hazelcast-node-3:
    image: hazelcast/hazelcast:latest
    restart: unless-stopped
    environment:
      HZ_NETWORK_JOIN: hazelcast-node-1,hazelcast-node-2
      JAVA_OPTS: -Dhazelcast.config=/opt/hazelcast/config/hazelcast.xml
    volumes:
      - "./hazeclast.xml:/opt/hazelcast/config/hazelcast.xml"
    ports:
      - "${PORT_NODE_HZ_3}:5701"
    networks:
      - hazelcast-lecture
    
  api-loggin-1:
    build: 
      context: .
      dockerfile: loggin.Dockerfile
    restart: unless-stopped
    environment:
      PORT_SEVICE: ${PORT_LOGGIN_MACHINE_1}
    ports:
      - "${PORT_LOGGIN_MACHINE_1}:${PORT_LOGGIN_MACHINE_1}"
    networks:
      - hazelcast-lecture

  api-loggin-2:
    build: 
      context: .
      dockerfile: loggin.Dockerfile
    restart: unless-stopped
    environment:
      PORT_SEVICE: ${PORT_LOGGIN_MACHINE_2}
    ports:
      - "${PORT_LOGGIN_MACHINE_2}:${PORT_LOGGIN_MACHINE_2}"
    networks:
      - hazelcast-lecture
    depends_on:
      - api-loggin-1

  api-loggin-3:
    build: 
      context: .
      dockerfile: loggin.Dockerfile
    restart: unless-stopped
    environment:
      PORT_SEVICE: ${PORT_LOGGIN_MACHINE_3}
    ports:
      - "${PORT_LOGGIN_MACHINE_3}:${PORT_LOGGIN_MACHINE_3}"
    networks:
      - hazelcast-lecture
    depends_on:
      - api-loggin-1
      - api-loggin-2

  api-facade:
    build: 
      context: .
      dockerfile: facade.Dockerfile
    restart: unless-stopped
    environment:
      PORT_SEVICE: ${PORT_FACADE_MACHINE}
      PORT_MESSAGE: ${PORT_MESSAGE_MACHINE}
      PORT_LOGGER_1: ${PORT_LOGGIN_MACHINE_1}
      PORT_LOGGER_2: ${PORT_LOGGIN_MACHINE_2}
      PORT_LOGGER_3: ${PORT_LOGGIN_MACHINE_3}
    ports:
      - "${PORT_FACADE_MACHINE}:${PORT_FACADE_MACHINE}"
    networks:
      - hazelcast-lecture

  api-message:
    build: 
      context: .
      dockerfile: message.Dockerfile
    restart: unless-stopped
    environment:
      PORT_SEVICE: ${PORT_MESSAGE_MACHINE}
    ports:
      - "${PORT_MESSAGE_MACHINE}:${PORT_MESSAGE_MACHINE}"
    networks:
      - hazelcast-lecture

  hazelcast-management-center:
    image: hazelcast/management-center:latest
    restart: unless-stopped
    environment:
      - HZ_MAN_CENTER_CLUSTER_MEMBERS=hazelcast-node-1:5701,hazelcast-node-2:5701,hazelcast-node-3:5701
    ports:
      - "8080:8080"
    networks:
      - hazelcast-lecture

networks:
  hazelcast-lecture:
    driver: bridge
